version: "3.7"

services:
  postgres:
    build:
      context: .
      dockerfile: docker/main/Dockerfile
    volumes:
      - ".:/src"

  django:
    volumes:
      - ".:/src"
    ports:
      - "127.0.0.1:8000:8000"

  nginx:
    volumes:
      - ".:/src"

  backup:
    volumes:
      - ".:/src"

  email_tasks:
    volumes:
      - ".:/src"

  # redis:
  #   volumes:
  #     - ".:/src"
  #
  # daphne:
  #   volumes:
  #     - ".:/src"
  #

  build_js:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}-node
    command: ["watch"]
    volumes:
      - ".:/src"
    env_file: .env
