# Generated by Django 2.1.3 on 2019-02-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyvaluestore',
            options={'verbose_name': 'Key-Value Pair', 'verbose_name_plural': 'Key-Value Store'},
        ),
    ]
